version: "3.9"

services:
  fileprocessor:
    build: .
    pull_policy: build  
    container_name: fileprocessor
    restart: unless-stopped

    # Needed for mounting inside container
    privileged: true
    cap_add:
      - SYS_ADMIN
