version: "3.9"

services:
  fileprocessor:
    image: myregistry.local/fileprocessor:latest
    pull_policy: always
    container_name: fileprocessor
    restart: unless-stopped

    privileged: true
    cap_add:
      - SYS_ADMIN

