version: "3.9"

services:
  fileprocessor:
    build:
      context: .
      dockerfile: Dockerfile
    image: fileprocessor_local:latest    # only local, not pushed anywhere
    container_name: fileprocessor

    restart: unless-stopped

    privileged: true
    cap_add:
      - SYS_ADMIN
